import React from 'react';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  cardWrapper: {
    backgroundColor: '#ffffff',
    margin: 10,
    borderRadius: 5,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 12,
  },
  cardBody: {
    display: 'flex',
    position: 'relative',
    padding: 10,
  },
  cardImage: {
    height: 260,
    width: '100%',
    backgroundColor: 'gray',
  },
  cardTitle: {
    textTransform: 'capitalize',
    fontSize: 22,
    fontWeight: 'bold',
    paddingRight: 55,
    marginBottom: 4,
  },
  cardText: {
    paddingBottom: 10,
  },
  cardFooter: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    marginTop: 5,
    marginBottom: 5,
  },
  avatarWrapper: {
    position: 'relative',
  },
  avatar: {
    position: 'absolute',
    height: 50,
    width: 50,
    borderRadius: 25,
    top: -25,
    right: 16,
  },
  actionWrapper: {
    position: 'absolute',
    top: 10,
    right: 10,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionText: {
    fontSize: 12,
    color: 'gray',
    paddingLeft: 8,
  },
  buttonWrapper: {
    elevation: 8,
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
    width: '100%',
    maxWidth: 120,
    height: 40,
    lineHeight: 40,
    borderRadius: 20,
    backgroundColor: '#0B57BF',
    textTransform: 'uppercase',
    marginLeft: 'auto',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  buttonText: {
    fontSize: 14,
    color: '#ffffff',
    alignSelf: 'center',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  addToCart: {
    marginLeft: 8,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.85)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveTool: {
    marginLeft: 'auto',
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.85)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  starCountWrapper: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  postedAt: {
    flexDirection: 'row',
  },
  priceUnitWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  price: {
    fontSize: 26,
    letterSpacing: -1,
    fontWeight: 'bold',
  },
  unit: {
    fontSize: 12,
    color: 'rgba(0, 0, 0, 0.5)',
    paddingLeft: 6,
  },
  toolImage: {
    ...StyleSheet.absoluteFillObject,
    // height: '100%',
    // width: '100%',
  },
  linearGradient: {
    flex: 1,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 5,
    opacity: 0.25,
  },
});
